const ShopActionTypes = {
    FETCH_START_ASYNC:"FETCH_START_ASYNC",
    FETCH_SUCCESSFULL_ASYNC:"FETCH_SUCCESSFULL_ASYNC",
    FETCH_FAILED_ASYNC:"FETCH_FAILED_ASYNC"
}

export default ShopActionTypes